# Generated by Django 3.1.3 on 2020-11-16 05:26

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_details', djongo.models.fields.JSONField()),
            ],
        ),
    ]
