# Generated by Django 3.0.5 on 2020-11-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20201116_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_user',
            name='username',
            field=models.TextField(max_length=25),
        ),
    ]
